POST http://127.0.0.1:8081/api/v1/jobs/direct
Content-Type: application/json
Accept: application/json

{
  "goals": [
    {
      "type": "inspect",
      "occurrenceType": "COLUMN"
    }
  ],
  "content": {
    "type": "reference-file",
    "files": [
      "s3://macie-data-471472241282-eu-central-1/hawk-dlp-example.csv"
    ]
  }
}